[zh-hans]
    languageName = "简体中文"
    contentDir = "content"
    weight = 1
    [zh-hans.params.head]
        tagline = "A Hugo Theme"
    [zh-hans.params.social]
        title = "Follow me"
        caption = "I work on everything coding and tweet developer memes"
    [zh-hans.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
